use Tarea6
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('513DB4C763RRO', 'PEMEX', 'Jenna', 93, 'Santa Rosa de Aguán', 24948);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('SQ9JNZMX8NTVL', 'Paylocity Holding Corporation', 'Dottie', 60, 'Futian', 84744);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('8XD8TVPBHF0XH', 'R1 RCM Inc.', 'Judy', 550, 'La Soledad', 62661);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('L9995XCO122HZ', 'iStar Financial Inc.', 'Farwell', 48, 'Yaozhuang', 19907);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('9BKFU39QJCDCM', 'Citrix Systems, Inc.', 'Kingsford', 0, 'Copa', 63537);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('Z4PZ1SZT33KYN', 'CA Inc.', 'Old Gate', 7, 'Nowy Tomysl', 75612);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('PAZ0RZEQ4QPJ8', 'The Cushing MLP Total Return Fund', 'Crowley', 15729, 'Concepción', 10112);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('TJ57E3GR3USL4', 'Highland Funds I', 'Buell', 4683, 'Akure', 70480);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('B06EMIVWEWAFC', 'CVR Energy Inc.', 'West', 65, 'Chelmza', 54531);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('VSDS414U6PGEY', 'Cumberland Pharmaceuticals Inc.', 'Meadow Valley', 88, 'Imatra', 55754);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('481L6PL6ULAVQ', 'Lehman ABS Corporation', 'Eagle Crest', 478, 'Lindome', 32583);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('TRR570INLEJBM', 'Boise Cascade, L.L.C.', '6th', 90, 'Timiryazevo', 27104);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('7UHDCTVQCRTWA', 'Triangle Capital Corporation', 'Meadow Vale', 6, 'Tucupita', 16999);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('9IY56JXTKC71F', 'Crescent Point Energy Corporation', 'Sutherland', 15, 'Houston', 75457);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('9Z3ZT4LVR2LY3', 'Tactile Systems Technology, Inc.', 'Almo', 4, 'Laiponda', 96380);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('B9H0OI8UJA0VX', 'H&E Equipment Services, Inc.', 'Superior', 19, 'Longhe', 69497);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('GXWPHL3BS5D5L', 'Tesoro Logistics LP', 'Hayes', 76, 'Åkersberga', 20675);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('PUDML2MEV7A8S', 'Valmont Industries, Inc.', 'Caliangt', 8345, 'Facatativá', 46471);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('SCPEDLLEOBHEQ', 'Xenetic Biosciences, Inc.', 'Eggendart', 3044, 'Lobatse', 24104);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('A8YWXLNMLBTP9', 'SPAR Group, Inc.', 'Fieldstone', 33169, 'Thành Ph? Bà R?a', 73039);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('DDD15UYXVZMS1', 'EnerNOC, Inc.', 'Orin', 8, 'Kórnik', 75017);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('4UPUD4CXI6Y4M', 'ABIOMED, Inc.', 'Warner', 5824, 'Buawan', 22514);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('DJZH461BNZTFN', 'USA Compression Partners, LP', 'Hudson', 11, 'Prince Rupert', 77346);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('CJVXEGUV08NA8', 'Antero Resources Corporation', 'Lillian', 5, 'Checacupe', 27977);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('M1M6H99TM2FJ6', 'Kelly Services, Inc.', 'Cambridge', 26, 'Katsuyama', 12382);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('CD87D7RD9SM83', 'Banco Santander, S.A.', 'Kim', 18, 'Tha Bo', 54567);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('6CRSY7ZHBCGHX', 'Banc of California, Inc.', 'Bellgrove', 7025, 'Chaumont', 29865);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('Z5Y6KURKE5OTG', 'First Trust Developed Markets ex-US Small Cap AlphaDEX Fund', 'Bluejay', 30, 'Austin', 19793);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('4F6G4EE9GYP6A', 'Dillard''s, Inc.', 'Anthes', 3, 'Orlovo', 42479);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('SE0G6H1P9IXL1', 'Horizon Global Corporation', 'Mallory', 2705, 'Vanadzor', 44817);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('Y4ZGHNXPVBCI8', 'Sprott Focus Trust, Inc.', 'Helena', 600, 'Dukla', 14198);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('K58NW8JVHFDVP', 'Graham Corporation', 'Longview', 18526, 'Chipoka', 57001);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('UT9TFWNGMR37I', 'Capitol Acquisition Corp. III', 'Roth', 57150, 'Sukaharja', 89879);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('NCWEQOHK7WPAN', 'Heska Corporation', 'Rowland', 83754, 'Krasnaya Polyana', 71754);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('QIDV5OT2WTGYB', 'Hibbett Sports, Inc.', 'Cottonwood', 8526, 'Olovyannaya', 92057);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('9HKBNX02TG2GE', 'Nuveen Quality Preferred Income Fund 2', 'Anniversary', 14, 'Tabuadelo', 98323);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('C2BKENPKFDBDT', 'US Ecology, Inc.', 'Ryan', 788, 'Pervoural’sk', 67019);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('TGOZCAUIAC12J', 'The Habit Restaurants, Inc.', 'Norway Maple', 285, 'Meilin', 99126);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('W14MHRWLELLQG', 'California Water  Service Group Holding', 'John Wall', 25328, 'Merefa', 72327);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('WS6ERT43PGQTA', 'CareDx, Inc.', 'Gina', 5, 'Ishioka', 37217);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('KOUDL4VRYSEZI', 'First Financial Bancorp.', 'Prairie Rose', 1, 'Stende', 70172);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('H1QXW6YVZ1VCD', 'Celadon Group, Inc.', 'Holy Cross', 40, 'Gorelki', 57459);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('OWB8QC2WXRL5A', 'Mitcham Industries, Inc.', 'Westridge', 5315, 'Wilcza', 33465);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('1LXC45LWLYYDW', 'Nuveen High Income December 2019 Target Term Fund', 'Utah', 4, 'Ronov nad Doubravou', 50369);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('U7U731PF4L7GT', 'Sempra Energy', 'Northview', 91, 'Veinticinco de Mayo', 95788);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('X70ZC2JKW3J6W', 'United States Cellular Corporation', 'Ridgeway', 6, 'Kuala Lumpur', 93538);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('BP938SD71BJX4', 'LM Funding America, Inc.', 'Sauthoff', 5, 'Nan’an', 25759);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('K490VEKTOTMLA', 'e.l.f. Beauty, Inc.', 'Lakewood Gardens', 3, 'Yanino Vtoroye', 96638);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('G1FRMCI696HW7', 'Invitation Homes Inc.', 'Division', 3, 'Xinxing', 10797);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('2YYU3CQGX0FLF', 'Macro Bank Inc.', 'Vermont', 17555, 'Bolembre', 61235);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('7ETIRII4YAEM5', 'On Track Innovations Ltd', 'Golf', 88, 'Verd', 65081);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('OQXV3F9KNE021', 'DDR Corp.', 'Mitchell', 2753, 'Verkhniy Landekh', 67843);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('MWAZ4D6JE7DJM', 'Rosehill Resources Inc.', 'Cambridge', 2802, 'Storozhynets’', 25605);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('LVJ31JUG6L6K8', 'Global X Health & Wellness Thematic ETF', 'Crescent Oaks', 92, 'Senahú', 21284);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('M7DS5D1N9EDFE', 'MYR Group, Inc.', 'Golf View', 3, 'Vyatskiye Polyany', 36811);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('6ROPGAXGOFS6E', 'Westar Energy, Inc.', 'Heath', 9388, 'Samobor', 53588);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('UPSZYPHRFVQNR', 'Allied World Assurance Company Holdings, AG', 'Forest Dale', 6697, 'Primorskiy', 83520);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('U44XH1WWPLKFR', 'Nucor Corporation', 'Memorial', 665, 'Concepción del Bermejo', 71063);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('TJ5KP7907YLGI', 'Endocyte, Inc.', 'Emmet', 47, 'Cakovec', 35434);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('9UYE42CKO5A2N', 'ESSA Bancorp, Inc.', 'Surrey', 7315, 'Xinbu', 70737);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('JBZ4VDGE6E6EY', 'Tower Semiconductor Ltd.', 'Crowley', 8, 'Selaphum', 98427);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('1REKW10CZ9P0K', 'Liberty Expedia Holdings, Inc.', 'Mccormick', 62, 'Kuantian', 75020);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('FTSLOYZ7M36OF', 'Raymond James Financial, Inc.', 'Ryan', 25098, 'Petersfield', 61755);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('3ZAP92AP6EQ8A', 'DarioHealth Corp.', 'Helena', 618, 'Lesozavodsk', 87806);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('NZUH0FZRM9TGB', 'Tocagen Inc.', 'Columbus', 34, 'Konarak', 61479);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('UW475T82UBTDC', 'MRC Global Inc.', 'Elka', 5, 'Agboville', 72614);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('CMPP73TMB8OHI', 'Appian Corporation', 'Ridge Oak', 16, 'Matou', 92959);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('GEY27W4MWPGIS', 'Tsakos Energy Navigation Ltd', 'Thompson', 2, 'Hanjia', 24830);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('Z5S8TF3HNDP61', 'Stemline Therapeutics, Inc.', 'Hollow Ridge', 2, 'Maogang', 89469);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('DACK2FNA44MIE', 'Senior Housing Properties Trust', 'Huxley', 6, 'Funga', 54976);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('NZGHNA6D9YG7A', 'Zions Bancorporation', 'Gina', 4241, 'Zeerust', 98919);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('RI3K40F4U5VTP', 'uniQure N.V.', 'Maple Wood', 72, 'Choujiang', 82148);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('091626ZQZVEJN', 'Alamos Gold Inc.', 'Emmet', 84, 'Georgetown', 97689);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('OHDZHXBMJ7K8H', 'Apptio, Inc.', 'Claremont', 4799, 'Varaždin', 38276);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('UV2OLYADR5I5R', 'First Trust Senior Loan Fund ETF', 'Dixon', 0, 'Anbyon-up', 88149);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('NRKZZDPLRA984', 'SteadyMed Ltd.', 'Ramsey', 47, 'Sharga', 45295);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('NQQOOV992GP75', 'THL Credit, Inc.', 'Manitowish', 2393, 'Kembé', 53827);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('4W9BOLQPZPP0T', 'Hersha Hospitality Trust', 'Buhler', 18149, 'Korsze', 20875);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('ZCL3CG3P38RBN', 'Spectrum Brands Holdings, Inc.', 'Roxbury', 47, 'Burbank', 49648);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('91UA69IUI0KA1', 'Continental Resources, Inc.', 'Little Fleur', 3953, 'Biên Hòa', 50777);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('HVVSW5LP85MHZ', 'Cable One, Inc.', 'Paget', 5875, 'Shenwan', 67183);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('9S439CDK9XQ4B', 'Alphabet Inc.', 'Farmco', 4848, 'Fumin', 85032);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('Y85GN1I536OJI', 'Associated Banc-Corp', 'Arkansas', 2, 'Inta', 38548);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('WZ8A0WLBH8TCY', 'Grifols, S.A.', 'Bowman', 926, 'Shahumyan', 23862);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('JAFOO1XO28BOZ', 'Tuesday Morning Corp.', 'Brickson Park', 9527, 'Panacan', 19706);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('C9SYI6HOF36L9', 'BB&T Corporation', 'Glendale', 77, 'Wrzesnia', 65713);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('IF7SASH1HBVDN', 'The Ensign Group, Inc.', 'Oneill', 1755, 'Toulon', 72362);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('DD39YW5UZAGAH', 'Franklin Resources, Inc.', 'Toban', 93, 'Montalegre', 54935);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('VXCOM5YRQ2380', 'Viavi Solutions Inc.', 'Sundown', 5, 'Tebon', 22246);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('VM8D9POP93BVB', 'Sonus Networks, Inc.', 'Marquette', 1420, 'Sobinka', 48769);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('YZWYZOPH7B9SS', 'Berry Global Group, Inc.', 'Buell', 74, 'Andrushivka', 90736);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('CTAZFG8Y5SK4L', 'Blackstone GSO Long Short Credit Income Fund', 'Artisan', 222, 'Vatutino', 56990);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('IDTRTRQ978AAS', 'IZEA Inc.', 'Shoshone', 5374, 'Boleszkowice', 63967);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('0ERZ84XEN5R61', 'Burlington Stores, Inc.', 'Brown', 0, 'San Francisco', 68440);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('P6YF4A2B7U4NF', 'Fortis Inc.', 'Norway Maple', 27356, 'Sampaio', 41439);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('AQG00POKZO26E', 'Fly Leasing Limited', 'Myrtle', 2569, 'Norrtälje', 89306);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('7NJ45VGPGBLJB', 'GMS Inc.', 'Leroy', 23831, 'Honglong', 31512);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('NUPKBSK3EAIA2', 'Global Partners LP', 'Kennedy', 3, 'Isaka', 55703);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('Z0N37GLPNKWUJ', 'CGI Group, Inc.', '1st', 9708, 'Norrköping', 47808);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('FEDRD5IIV08NP', 'Hamilton Bancorp, Inc.', 'Texas', 86, 'Tha Tako', 98729);
