insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('PRUEBA1234567', 'PEMEX', 'Crowley', 4257, 'Qandahar', 21948);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('6SU71PCZJ5DYS', 'Gladstone Investment Corporation', 'Everett', 7, 'South Hill', 59571);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('QB4VT6KBYQF7K', 'EPAM Systems, Inc.', 'Eagan', 9, 'Almirante Brown', 56730);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('8I2HFO0MDD1Z2', 'Progressive Corporation (The)', '4th', 27, 'La Matanza', 84833);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('BBA264L3FCDJH', 'First Trust Low Beta Income ETF', 'Spenser', 6, 'Sidi Bel Abbès', 30096);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('U618DJTEYORMT', 'EPAM Systems, Inc.', 'Almo', 3, 'Ech-Chleff (el-Asnam)', 54164);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('NK3MJG41QM4GA', 'Global X Longevity Thematic ETF', 'Moulton', 7, 'Esteban Echeverría', 35141);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('ZIS4XVP16VPIM', 'Access National Corporation', 'Fremont', 4, 'Escobar', 68365);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('LZ644ZLFRB2LN', 'Marathon Patent Group, Inc.', 'Prairie Rose', 9, 'Constantine', 13343);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('A6PQUI54VWZTP', 'BJ''s Restaurants, Inc.', 'Cordelia', 68275, 'Herat', 27644);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('WDXRBLWH4FA41', 'Gulf Resources, Inc.', 'Moulton', 2, 'Berazategui', 35322);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('MM0RRM52MD6LZ', 'Cohen & Steers Limited Duration Preferred and Income Fund, Inc', 'Del Mar', 6, 'Ghardaïa', 21712);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('QWQEJ5YKFKRMJ', 'Westlake Chemical Partners LP', 'Randy', 6845, 'Namibe', 44696);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('E89X8IVBPOMNU', 'Templeton Emerging Markets Income Fund, Inc.', 'Linden', 4, 'Tirana', 94480);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('BN0Y23XX4Z2J1', 'Houghton Mifflin Harcourt Company', 'Reindahl', 13, 'Andorra la Vella', 96276);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('EEG1OETXTGICC', 'Bank of N.T. Butterfield & Son Limited (The)', 'Rutledge', 2945, 'Annaba', 90688);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('O2YNWRWBVLMQE', 'Altimmune, Inc.', 'Randy', 6845, 'Namibe', 44696);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('BFEX41T96NWGC', 'Nustar Energy L.P.', 'Kings', 177, 'Tlemcen (Tilimsen)', 92627);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('O1LTZCLWD9GZJ', 'FlexShares Credit-Scored US Corporate Bond Index Fund', 'Comanche', 2, 'Ech-Chleff (el-Asnam)', 23630);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('E4MSDEBKAUBYA', 'Kellogg Company', 'Melby', 2737, 'Saint John´s', 62789);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('V0QBCMAPL0D44', 'TEGNA Inc.', 'Rutledge', 2945, 'Annaba', 90688);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('S1DVL53737RVS', 'The Dixie Group, Inc.', 'Hollow Ridge', 16, 'Qandahar', 79109);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('CZZNITUJF6ZUJ', 'PowerShares DWA Healthcare Momentum Portfolio', 'Golf', 7574, 'Herat', 59891);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('JGK9BKOUNOC77', 'DTE Energy Company', 'Vidon', 6, 'Namibe', 43864);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('ZQAHE01KX41K4', 'Truett-Hurst, Inc.', 'Riverside', 3234, 'Biskra', 13607);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('YEVBGI3FJWWNW', 'Helix Energy Solutions Group, Inc.', 'Calypso', 27671, 'Batna', 62742);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('2CI4G1TOW1C7G', 'Kayne Anderson Acquisition Corp.', 'Declaration', 81494, 'The Valley', 52993);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('L0G6AVVXL39ZD', 'JA Solar Holdings, Co., Ltd.', 'Kim', 3122, 'General San Martín', 84297);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('QLDOKSZOCXHTE', 'Kinsale Capital Group, Inc.', 'Hollow Ridge', 16, 'Qandahar', 79109);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('SHP5IVM8CKH9O', 'Southern National Bancorp of Virginia, Inc.', 'Fremont', 64566, 'Blida (el-Boulaida)', 48542);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('HTJDTAN38KQ1M', 'United-Guardian, Inc.', 'Jackson', 965, 'Tirana', 80161);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('T15NE10BE408V', 'TransAct Technologies Incorporated', 'Miller', 544, 'Qandahar', 34286);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('ARUEM8PLJTP28', 'Celadon Group, Inc.', 'Grayhawk', 1005, 'La Plata', 84058);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('Z7LTSEWA8CE69', 'Select Income REIT', 'Evergreen', 8, 'Sidi Bel Abbès', 32915);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('LTRSX4RHV07L0', 'PerkinElmer, Inc.', 'Dennis', 28883, 'Andorra la Vella', 18684);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('B6G8VOZWTOIJR', 'MB Financial Inc.', 'Prentice', 80, 'Ech-Chleff (el-Asnam)', 19780);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('P77CU5U4H6RI5', 'ASML Holding N.V.', 'Kim', 3122, 'General San Martín', 84297);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('05S981B7J5LZJ', 'Hebron Technology Co., Ltd.', 'Brentwood', 2218, 'CDMX', 12046);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('IEJX2ZH42UYF7', 'CABCO Series 2004-101 Trust', 'Carpenter', 65332, 'Skikda', 53578);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('ZAZ935VCHAD29', 'Mobile Mini, Inc.', 'Sachs', 22, 'Batna', 81366);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('ZKCOYROFDXVKW', 'Horizon Technology Finance Corporation', 'Coolidge', 1770, 'General San Martín', 91098);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('UMNHPXIXM314H', 'Infinity Property and Casualty Corporation', '3rd', 6, 'Saint John´s', 10068);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('3W97LSW9P09CY', 'Public Storage', 'Mcbride', 8646, 'Lanús', 40935);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('L57WMU3XYEW1X', 'BSQUARE Corporation', 'Killdeer', 8841, 'Sétif', 58952);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('G5TWEJDU2KNFN', 'Eaton Vance Tax-Managed Buy-Write Income Fund', 'Kipling', 4896, 'Ghardaïa', 52306);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('ROGFEZ7JPVMXD', 'Old Republic International Corporation', 'Browning', 57, 'Namibe', 30279);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('M927GTDJXFK3Z', 'Berkshire Hills Bancorp, Inc.', 'American', 4221, 'Bahía Blanca', 10284);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('9CQ8TP4IZ6HZJ', 'Simulations Plus, Inc.', 'Eggendart', 3, 'Lobito', 42620);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('KMJ4XMJRLI0C2', 'PowerShares Dividend Achievers Portfolio', 'Hovde', 5, 'Esteban Echeverría', 14369);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('4PERHSD3HOMHH', 'Retail Properties of America, Inc.', 'Kim', 3122, 'General San Martín', 84297);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('XJG0IAKTUUNI0', 'Bank Of Montreal', 'Almo', 3, 'Ech-Chleff (el-Asnam)', 54164);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('51MF1GF89GLDA', 'Green Plains Partners LP', 'Roth', 9, 'Skikda', 91966);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('HA4758269KKAC', 'Invesco Bond Fund', 'Menomonie', 58, 'Ezeiza', 26649);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('V19RP8YNGM863', 'Norwegian Cruise Line Holdings Ltd.', 'Columbus', 1, 'José C. Paz', 59381);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('RLGJWTAM70PZG', 'Gulf Resources, Inc.', 'Hagan', 3, 'Mostaganem', 80788);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('HST4PDNYGFICK', 'First Horizon National Corporation', 'Derek', 3, 'Mostaganem', 43464);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('C06H1EBK469EY', 'Principal Real Estate Income Fund', 'Hansons', 6550, 'Tébessa', 37447);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('OC7BSA26HC6I8', 'Newell Brands Inc.', '3rd', 6, 'Saint John´s', 10068);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('CQGOTYFMVBIJC', 'Ryman Hospitality Properties, Inc.', 'Farmco', 48543, 'Oran', 10670);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('08EOM6T288Y5D', 'VictoryShares International Volatility Wtd ETF', 'Mitchell', 1, 'Oran', 65054);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('KJ97APV9PPIAA', 'News Corporation', 'Little Fleur', 21, 'Qandahar', 59551);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('CNLG77BMZMVR8', 'Healthcare Trust of America, Inc.', 'Cottonwood', 61, 'La Matanza', 30264);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('OFM79HFHL76Z6', 'Whirlpool Corporation', 'Carpenter', 65332, 'Skikda', 53578);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('TKFY22Z504KPS', 'Taubman Centers, Inc.', 'Old Shore', 353, 'Hurlingham', 37572);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('R1VNYAJSD1MVP', 'DTE Energy Company', 'Randy', 26052, 'Hurlingham', 55086);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('XBKX23DQXLEBQ', 'Marsh & McLennan Companies, Inc.', 'Morningstar', 782, 'Tirana', 85543);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('C6QTO4MGD56L1', 'Enduro Royalty Trust', 'Longview', 4025, 'Oran', 67306);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('0KJHZL0O4NCKG', 'Anheuser-Busch Inbev SA', 'Buell', 710, 'General San Martín', 85377);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('YCXIMGSIUV1LM', 'Carrizo Oil & Gas, Inc.', 'Marcy', 219, 'Alger', 43179);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('Q4EBN0DCPVRON', 'AxoGen, Inc.', 'Milwaukee', 0, 'Herat', 59774);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('TE4EUNKZP0QNH', 'Principal Millennials Index ETF', 'Thackeray', 25, 'Alger', 82567);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('BVIUZ5MQIQFDT', 'Sussex Bancorp', 'Fairfield', 29, 'Skikda', 44736);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('RJ9PPC5OTRIJ0', 'Lithia Motors, Inc.', 'Gina', 6, 'Hurlingham', 55016);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('NBQEGGHX7IJCY', 'Applied Industrial Technologies, Inc.', 'La Follette', 6, 'Tafuna', 44807);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('U8VNMPK6R0IT7', 'AllianzGI NFJ Dividend, Interest & Premium Strategy Fund', 'Dwight', 6, 'Fagatogo', 57798);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('ECBF7XSY2YSN6', 'CVR Refining, LP', 'Harper', 43527, 'Esteban Echeverría', 73721);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('PL81PSTKEMOKC', 'First Trust Strategic High Income Fund II', 'Crowley', 4257, 'Qandahar', 21948);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('WXJAOD144FEGH', 'Amazon.com, Inc.', 'Clarendon', 55635, 'Berazategui', 20864);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('88UQ5Q60P34WK', 'Ominto, Inc.', 'Kim', 3122, 'General San Martín', 84297);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('KT8684V4WNDT1', 'CSX Corporation', 'Pawling', 20118, 'Ituzaingó', 51123);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('R0SRAGJ8ST95Q', 'TriMas Corporation', 'Chinook', 7608, 'Oran', 64672);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('3LPD2KD9Z16X0', 'New York Mortgage Trust, Inc.', 'Cottonwood', 9683, 'Ituzaingó', 48409);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('ZEIHYEULH0DB1', 'L.B. Foster Company', 'Thompson', 13, 'Kabul', 35691);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('2EW38D3D55DU0', 'Popular, Inc.', 'Buhler', 28, 'Benguela', 73314);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('0C389I7JDN2GM', 'Nuveen Pennsylvania Quality Municipal Income Fund', 'Reinke', 247, 'Ezeiza', 83728);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('DJ8L5GMCHDAOX', 'Diffusion Pharmaceuticals Inc.', 'Hovde', 5, 'Esteban Echeverría', 14369);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('ZRMOYS2B9CRW3', 'Opko Health, Inc.', 'Little Fleur', 744, 'Tiaret', 29041);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('I0NCF8L06WES3', 'Intra-Cellular Therapies Inc.', 'Melby', 383, 'Ituzaingó', 13459);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('Q1K9MH72AAPKX', 'Korea Electric Power Corporation', 'Dovetail', 98, 'Almirante Brown', 88074);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('B85G1CDE45W0H', 'The GDL Fund', 'Washington', 61549, 'Béchar', 67261);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('CLT2B1Q76TF8B', 'Western Asset High Income Opportunity Fund, Inc.', 'Coleman', 725, 'Tlemcen (Tilimsen)', 23162);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('FS0OWNU2RWMXB', 'Easterly Government Properties, Inc.', 'Gerald', 93, 'Sétif', 27940);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('6AU4B3K6YKEH9', 'Global Indemnity Limited', 'Boyd', 2, 'Oran', 50659);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('KZ0VAY9U4L17L', 'Zix Corporation', 'Cottonwood', 61, 'La Matanza', 30264);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('QGFLIO83B52JS', 'Valvoline Inc.', 'Moulton', 5, 'Andorra la Vella', 77552);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('IE7K48BTUXV0B', 'Yatra Online, Inc.', 'Barnett', 7204, 'Berazategui', 35612);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('772L8W9PNPRY1', 'New York Community Bancorp, Inc.', 'Debra', 400, 'General San Martín', 66452);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('AZUWKWYP94WYI', 'Stoneridge, Inc.', 'Esker', 714, 'Sidi Bel Abbès', 21020);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('JUG56Q2OXSV5R', 'Fresenius Medical Care Corporation', 'Kenwood', 2790, 'Lanús', 83484);
insert into Empresa (RFC, razonSocial, calle, num, ciudad, CPE) values ('C616OWHY7HQAO', 'Entergy Louisiana, Inc.', 'Grim', 4289, 'Hurlingham', 26851);
