insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (3732, 'Analiese', 'Warrior', 'Erie', '06443', 41144);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (7173, 'Rollo', 'Briar Crest', 'Maple Wood', '96087', 38064);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (4728, 'Glennie', 'Sunnyside', 'Eastlawn', '5', 69871);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (1436, 'Kippy', 'Washington', 'Boyd', '94', 86893);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (2995, 'Carling', 'Kinsman', 'Homewood', '0', 17043);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (6692, 'Charin', 'Weeping Birch', 'Bartelt', '9', 16277);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (9556, 'Hiram', 'Hazelcrest', 'Carpenter', '105', 89933);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (3781, 'Odelia', 'Crownhardt', 'Kenwood', '42', 64155);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (4493, 'Orel', 'Rieder', 'Melby', '49101', 40355);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (3330, 'Phillip', 'Ludington', 'Moulton', '1', 63305);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (8241, 'Gawain', 'Rowland', 'Rowland', '1158', 73623);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (3852, 'Maggy', 'Havey', 'Quincy', '8546', 37754);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (1271, 'Isidor', 'Basil', 'Anhalt', '39241', 87847);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (5498, 'Colin', 'Dryden', 'School', '0', 17177);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (7637, 'Chiarra', 'Gale', 'Swallow', '5665', 28627);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (9400, 'Wally', '6th', 'Shopko', '59771', 90549);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (5995, 'Alejandrina', 'Grim', 'Oxford', '8628', 22419);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (6148, 'Gerrard', 'Manley', 'Schurz', '987', 29258);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (6179, 'Carmen', 'Springview', 'Blackbird', '972', 45838);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (6254, 'Carey', 'Paget', 'Eggendart', '52348', 47127);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (9902, 'Daphna', 'Northwestern', 'Corscot', '609', 81753);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (9522, 'Katey', 'Sherman', 'Oriole', '2', 86723);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (4314, 'Charmian', 'Little Fleur', 'Elgar', '084', 57594);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (2124, 'Harlin', 'Melvin', 'Nobel', '3', 65570);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (4838, 'Iormina', 'Lotheville', 'John Wall', '38143', 91183);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (2123, 'Grantley', 'Anthes', 'Esker', '712', 97930);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (8219, 'Lek', 'Hanover', 'Magdeline', '53647', 42239);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (7093, 'Myrna', 'Mosinee', 'Lawn', '5', 96277);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (1524, 'Fulvia', 'Mandrake', 'Atwood', '930', 54936);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (2949, 'Lida', 'Dryden', 'Everett', '5811', 96920);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (6080, 'Yancey', 'Raven', 'Southridge', '5180', 15140);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (8061, 'Aaron', 'Holmberg', 'Kim', '40', 77627);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (8254, 'Ruby', 'Golden Leaf', 'Anniversary', '60910', 73815);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (9962, 'Tedra', 'Delaware', 'Blaine', '62', 16236);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (4490, 'Pascal', 'Anniversary', 'Homewood', '75', 65129);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (6520, 'Kat', 'Namekagon', 'Maryland', '7809', 78723);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (1175, 'Garvy', 'Del Sol', 'Grayhawk', '5', 20773);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (1919, 'Miranda', 'Kim', 'Prentice', '391', 50004);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (4042, 'Anderson', 'Lakeland', 'Cascade', '981', 91321);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (2499, 'Deb', 'Cascade', 'Annamark', '291', 13857);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (8201, 'Jordon', 'Utah', 'Hermina', '28', 17929);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (1743, 'Malynda', 'Raven', 'Stone Corner', '136', 21389);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (5075, 'Freeland', 'Bluejay', 'Kingsford', '016', 56545);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (4861, 'Daune', 'Artisan', 'Everett', '20', 88518);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (6407, 'Pasquale', 'Northwestern', 'Harbort', '81470', 37332);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (9523, 'Dun', 'Chive', 'Gulseth', '7615', 21210);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (3333, 'Keen', 'Lukken', 'Mandrake', '8', 62054);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (2251, 'Allie', 'Arizona', 'Scott', '1', 37316);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (7294, 'Gertrudis', 'Elka', 'Fallview', '91196', 42310);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (6549, 'Karlen', 'Ohio', 'Milwaukee', '3', 13141);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (9858, 'Sinclare', 'Novick', 'Kennedy', '5', 80041);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (7297, 'Darbie', 'Lake View', 'Stone Corner', '05', 14522);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (7929, 'Tyler', 'Roxbury', 'Claremont', '56753', 26297);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (5626, 'Kin', 'Northwestern', 'Eagan', '85602', 27706);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (1198, 'Blythe', 'Thierer', 'Porter', '250', 19258);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (8896, 'Scot', '7th', 'Marcy', '15113', 80561);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (6552, 'Jere', 'Shasta', 'Grim', '006', 19897);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (4932, 'Lennard', 'Cherokee', 'Londonderry', '41', 20558);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (6015, 'Sonja', 'Golf Course', 'Buell', '7417', 78616);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (3824, 'Teri', 'Shoshone', 'Oneill', '14', 34820);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (5382, 'Currey', 'Kennedy', 'Kings', '4967', 23539);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (8671, 'Cacilia', 'Valley Edge', 'Upham', '963', 64503);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (4933, 'Lewiss', 'Crest Line', 'Straubel', '177', 17019);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (5282, 'Gaven', 'Evergreen', 'South', '98628', 95385);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (8311, 'Dyana', 'Canary', 'Utah', '91', 33899);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (5313, 'Tish', 'Elgar', 'Pearson', '93269', 79991);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (7157, 'Estevan', 'La Follette', 'Mitchell', '13641', 67033);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (6128, 'Krissie', 'Pearson', 'Ridgeway', '2', 82647);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (2617, 'Troy', 'Rockefeller', 'Talisman', '442', 20521);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (2165, 'Frederic', 'Londonderry', 'Hanson', '8597', 91576);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (2802, 'Sayre', 'Anniversary', 'Browning', '86', 54731);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (2014, 'Cesya', 'Mosinee', 'Fulton', '9', 98948);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (9387, 'Shani', 'Commercial', 'Lighthouse Bay', '17', 53971);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (5986, 'Lulu', 'Cascade', 'Warner', '6164', 93064);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (8004, 'Torry', 'Texas', 'Kim', '3546', 63346);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (1325, 'Tamqrah', 'Sachs', 'Tony', '4', 34616);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (4000, 'Tobe', 'Rigney', 'Mitchell', '0744', 34711);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (3879, 'Abraham', 'Alpine', 'Hintze', '96', 63647);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (4302, 'Clarisse', 'Bay', 'Toban', '68', 16056);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (6378, 'Rae', 'Crest Line', 'Macpherson', '34', 17783);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (4027, 'Andonis', 'Banding', 'Elmside', '344', 41238);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (9025, 'Korella', 'Maywood', 'Hoffman', '6', 77772);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (5052, 'Rena', 'Bluestem', 'Blue Bill Park', '19560', 89897);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (8054, 'Tate', 'Pearson', 'High Crossing', '2041', 19859);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (2073, 'Drusie', 'Scoville', 'Spaight', '97', 77819);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (5249, 'Conny', 'Continental', 'Drewry', '91', 93549);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (7381, 'Dino', 'Quincy', 'Autumn Leaf', '67615', 75297);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (5829, 'Charmine', 'Claremont', 'Merry', '958', 29873);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (5112, 'Herta', 'Oak', '7th', '65', 92760);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (8047, 'Yvette', 'Anhalt', 'Haas', '538', 47110);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (6054, 'Craggy', 'Ohio', 'Prairie Rose', '8089', 77129);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (5481, 'Pietro', 'Calypso', 'Vermont', '0', 45685);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (7250, 'Tremaine', 'Dwight', 'Hoffman', '3', 27623);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (3379, 'Berri', 'Corry', 'Ronald Regan', '1688', 13180);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (6507, 'Hedvig', 'Riverside', 'Sutherland', '8', 21745);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (6600, 'Quentin', '1st', 'Stephen', '798', 78619);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (7001, 'Pier', 'Carioca', 'Manufacturers', '719', 61076);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (7178, 'Darryl', 'Northwestern', 'Jenna', '71151', 69172);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (5220, 'Vlad', 'Swallow', 'Redwing', '26', 76592);
insert into ClienteE (idClienteE, nombre, calle, avenida, numExt, CPC) values (1165, 'Merrie', 'Darwin', 'West', '987', 70420);
