insert into Ingredientes (idPlatillo, ingrediente) values (1, 'Sea Bass - Fillets');
insert into Ingredientes (idPlatillo, ingrediente) values (2, 'Oats Large Flake');
insert into Ingredientes (idPlatillo, ingrediente) values (3, 'Cheese - Pied De Vents');
insert into Ingredientes (idPlatillo, ingrediente) values (4, 'Tuna - Yellowfin');
insert into Ingredientes (idPlatillo, ingrediente) values (5, 'Cheese - Swiss Sliced');
insert into Ingredientes (idPlatillo, ingrediente) values (6, 'Cup - 8oz Coffee Perforated');
insert into Ingredientes (idPlatillo, ingrediente) values (7, 'Wine - White, Riesling, Semi - Dry');
insert into Ingredientes (idPlatillo, ingrediente) values (8, 'Sauce Bbq Smokey');
insert into Ingredientes (idPlatillo, ingrediente) values (9, 'Bread - Pita');
insert into Ingredientes (idPlatillo, ingrediente) values (10, 'Paper Towel Touchless');
insert into Ingredientes (idPlatillo, ingrediente) values (11, 'Shrimp - Prawn');
insert into Ingredientes (idPlatillo, ingrediente) values (12, 'Bagels Poppyseed');
insert into Ingredientes (idPlatillo, ingrediente) values (13, 'Beets - Golden');
insert into Ingredientes (idPlatillo, ingrediente) values (14, 'Laundry - Bag Cloth');
insert into Ingredientes (idPlatillo, ingrediente) values (15, 'Turkey - Breast, Boneless Sk On');
insert into Ingredientes (idPlatillo, ingrediente) values (1, 'Tomatoes Tear Drop');
insert into Ingredientes (idPlatillo, ingrediente) values (2, 'Cognac - Courvaisier');
insert into Ingredientes (idPlatillo, ingrediente) values (3, 'Table Cloth 62x114 Colour');
insert into Ingredientes (idPlatillo, ingrediente) values (4, 'Tea - Lemon Scented');
insert into Ingredientes (idPlatillo, ingrediente) values (5, 'Garlic Powder');
insert into Ingredientes (idPlatillo, ingrediente) values (6, 'Salmon - Fillets');
insert into Ingredientes (idPlatillo, ingrediente) values (7, 'Yogurt - Strawberry, 175 Gr');
insert into Ingredientes (idPlatillo, ingrediente) values (8, 'Cake - French Pear Tart');
insert into Ingredientes (idPlatillo, ingrediente) values (9, 'Nut - Pecan, Halves');
insert into Ingredientes (idPlatillo, ingrediente) values (10, 'Cotton Wet Mop 16 Oz');
insert into Ingredientes (idPlatillo, ingrediente) values (11, 'Lemonade - Mandarin, 591 Ml');
insert into Ingredientes (idPlatillo, ingrediente) values (12, 'Salmon Steak - Cohoe 6 Oz');
insert into Ingredientes (idPlatillo, ingrediente) values (13, 'Pepper - Yellow Bell');
insert into Ingredientes (idPlatillo, ingrediente) values (14, 'Spinach - Packaged');
insert into Ingredientes (idPlatillo, ingrediente) values (15, 'Sauce - Caesar Dressing');
insert into Ingredientes (idPlatillo, ingrediente) values (1, 'Sausage - Chorizo');
insert into Ingredientes (idPlatillo, ingrediente) values (2, 'Lamb Leg - Bone - In Nz');
insert into Ingredientes (idPlatillo, ingrediente) values (3, 'Waffle Stix');
insert into Ingredientes (idPlatillo, ingrediente) values (4, 'Asparagus - Mexican');
insert into Ingredientes (idPlatillo, ingrediente) values (5, 'Mousse - Mango');
insert into Ingredientes (idPlatillo, ingrediente) values (6, 'Shiro Miso');
insert into Ingredientes (idPlatillo, ingrediente) values (7, 'Garlic Powder');
insert into Ingredientes (idPlatillo, ingrediente) values (8, 'Banana Turning');
insert into Ingredientes (idPlatillo, ingrediente) values (9, 'Oil - Macadamia');
insert into Ingredientes (idPlatillo, ingrediente) values (10, 'Cabbage - Savoy');
insert into Ingredientes (idPlatillo, ingrediente) values (11, 'Pasta - Ravioli');
insert into Ingredientes (idPlatillo, ingrediente) values (12, 'Halibut - Fletches');
insert into Ingredientes (idPlatillo, ingrediente) values (13, 'Juice - V8, Tomato');
insert into Ingredientes (idPlatillo, ingrediente) values (14, 'Bouillion - Fish');
insert into Ingredientes (idPlatillo, ingrediente) values (15, 'Foam Espresso Cup Plain White');
insert into Ingredientes (idPlatillo, ingrediente) values (1, 'Cup - 4oz Translucent');
insert into Ingredientes (idPlatillo, ingrediente) values (2, 'Veal - Eye Of Round');
insert into Ingredientes (idPlatillo, ingrediente) values (3, 'Wine - Chenin Blanc K.w.v.');
insert into Ingredientes (idPlatillo, ingrediente) values (4, 'Dragon Fruit');
insert into Ingredientes (idPlatillo, ingrediente) values (5, 'Filling - Mince Meat');
