insert into ProductoPerecedor (idProducto, nombreProducto, precio, marca) values ('9505', 'Steam Pan - Half Size Deep', '$226.25', 'Rush Enterprises, Inc.');
insert into ProductoPerecedor (idProducto, nombreProducto, precio, marca) values ('3821', 'Flavouring - Orange', '$216.15', 'MDC Partners Inc.');
insert into ProductoPerecedor (idProducto, nombreProducto, precio, marca) values ('2834', 'Snapple Raspberry Tea', '$213.18', 'Invesco Credit Opportunities Fund');
insert into ProductoPerecedor (idProducto, nombreProducto, precio, marca) values ('2776', 'Iced Tea - Lemon, 460 Ml', '$298.83', 'Cellect Biotechnology Ltd.');
insert into ProductoPerecedor (idProducto, nombreProducto, precio, marca) values ('7338', 'Halibut - Steaks', '$132.39', 'Eagle Materials Inc');
insert into ProductoPerecedor (idProducto, nombreProducto, precio, marca) values ('8575', 'Tomato - Peeled Italian Canned', '$102.29', 'Salient Midstream & MLP Fund');
insert into ProductoPerecedor (idProducto, nombreProducto, precio, marca) values ('5255', 'Spring Roll Veg Mini', '$290.84', 'Quest Resource Holding Corporation.');
insert into ProductoPerecedor (idProducto, nombreProducto, precio, marca) values ('3508', 'Scrubbie - Scotchbrite Hand Pad', '$239.08', 'Lamb Weston Holdings, Inc.');
insert into ProductoPerecedor (idProducto, nombreProducto, precio, marca) values ('6332', 'Flower - Commercial Spider', '$165.99', 'Seaspan Corporation');
insert into ProductoPerecedor (idProducto, nombreProducto, precio, marca) values ('2055', 'Grapes - Black', '$97.85', 'Perfumania Holdings, Inc');
insert into ProductoPerecedor (idProducto, nombreProducto, precio, marca) values ('7971', 'Savory', '$151.10', 'Senior Housing Properties Trust');
insert into ProductoPerecedor (idProducto, nombreProducto, precio, marca) values ('8981', 'Pastry - Plain Baked Croissant', '$68.54', 'Telephone and Data Systems, Inc.');
insert into ProductoPerecedor (idProducto, nombreProducto, precio, marca) values ('4666', 'Pork - Ham Hocks - Smoked', '$259.86', 'First Merchants Corporation');
insert into ProductoPerecedor (idProducto, nombreProducto, precio, marca) values ('2698', 'Pur Value', '$90.16', 'PhotoMedex, Inc.');
insert into ProductoPerecedor (idProducto, nombreProducto, precio, marca) values ('1253', 'Glove - Cutting', '$284.02', 'FlexShares Credit-Scored US Corporate Bond Index Fund');
insert into ProductoPerecedor (idProducto, nombreProducto, precio, marca) values ('5237', 'Glaze - Apricot', '$249.48', 'Nustar Energy L.P.');
insert into ProductoPerecedor (idProducto, nombreProducto, precio, marca) values ('6695', 'Momiji Oroshi Chili Sauce', '$287.63', 'International Bancshares Corporation');
insert into ProductoPerecedor (idProducto, nombreProducto, precio, marca) values ('2225', 'Bar Nature Valley', '$225.54', 'Oritani Financial Corp.');
insert into ProductoPerecedor (idProducto, nombreProducto, precio, marca) values ('1666', 'Chives - Fresh', '$117.04', 'Stag Industrial, Inc.');
insert into ProductoPerecedor (idProducto, nombreProducto, precio, marca) values ('9720', 'Beef - Ground, Extra Lean, Fresh', '$135.91', 'Cousins Properties Incorporated');
