insert into ProductoNoPerecedor (idProducto, nombreProducto, precio, marca, fechaCaducidad) values ('0397', 'Milk - Skim', '$132.95', 'ServiceMaster Global Holdings, Inc.', '12/11/2019');
insert into ProductoNoPerecedor (idProducto, nombreProducto, precio, marca, fechaCaducidad) values ('8191', 'Tea Peppermint', '$99.44', 'Eltek Ltd.', '12/19/2019');
insert into ProductoNoPerecedor (idProducto, nombreProducto, precio, marca, fechaCaducidad) values ('4975', 'Chef Hat 25cm', '$79.83', 'Landmark Infrastructure Partners LP', '12/26/2019');
insert into ProductoNoPerecedor (idProducto, nombreProducto, precio, marca, fechaCaducidad) values ('2817', 'Orange - Tangerine', '$134.03', 'MSC Industrial Direct Company, Inc.', '12/29/2019');
insert into ProductoNoPerecedor (idProducto, nombreProducto, precio, marca, fechaCaducidad) values ('5238', 'Sugar - Brown', '$167.37', 'State Street Corporation', '12/15/2019');
insert into ProductoNoPerecedor (idProducto, nombreProducto, precio, marca, fechaCaducidad) values ('6230', 'Wine - Red, Lurton Merlot De', '$186.91', 'Athene Holding Ltd.', '12/19/2019');
insert into ProductoNoPerecedor (idProducto, nombreProducto, precio, marca, fechaCaducidad) values ('1038', 'Lobster - Live', '$283.33', 'VSE Corporation', '12/23/2019');
insert into ProductoNoPerecedor (idProducto, nombreProducto, precio, marca, fechaCaducidad) values ('0660', 'Sugar - Brown, Individual', '$174.36', 'Blackrock Florida Municipal 2020 Term Trust', '12/15/2019');
insert into ProductoNoPerecedor (idProducto, nombreProducto, precio, marca, fechaCaducidad) values ('7475', 'Snails - Large Canned', '$64.82', 'Chanticleer Holdings, Inc.', '12/26/2019');
insert into ProductoNoPerecedor (idProducto, nombreProducto, precio, marca, fechaCaducidad) values ('0833', 'Cake - Dulce De Leche', '$247.78', 'Franklin Covey Company', '12/29/2019');
insert into ProductoNoPerecedor (idProducto, nombreProducto, precio, marca, fechaCaducidad) values ('3688', 'Garbage Bags - Black', '$259.85', 'LPL Financial Holdings Inc.', '12/25/2019');
insert into ProductoNoPerecedor (idProducto, nombreProducto, precio, marca, fechaCaducidad) values ('4788', 'Cheese - Brie Roitelet', '$230.43', 'TD Ameritrade Holding Corporation', '12/21/2019');
insert into ProductoNoPerecedor (idProducto, nombreProducto, precio, marca, fechaCaducidad) values ('8394', 'Nantucket - Pomegranate Pear', '$235.84', 'GenVec, Inc.', '12/09/2019');
insert into ProductoNoPerecedor (idProducto, nombreProducto, precio, marca, fechaCaducidad) values ('6193', 'Tart Shells - Barquettes, Savory', '$205.88', 'Nova Measuring Instruments Ltd.', '12/22/2019');
insert into ProductoNoPerecedor (idProducto, nombreProducto, precio, marca, fechaCaducidad) values ('7035', 'Myers Planters Punch', '$297.11', 'Reading International Inc', '12/16/2019');
insert into ProductoNoPerecedor (idProducto, nombreProducto, precio, marca, fechaCaducidad) values ('9145', 'Lobster - Canned Premium', '$108.51', 'Sohu.com Inc.', '12/27/2019');
insert into ProductoNoPerecedor (idProducto, nombreProducto, precio, marca, fechaCaducidad) values ('1473', 'Magnotta - Bel Paese White', '$73.16', 'Alaska Communications Systems Group, Inc.', '12/21/2019');
insert into ProductoNoPerecedor (idProducto, nombreProducto, precio, marca, fechaCaducidad) values ('0317', 'Berry Brulee', '$52.24', 'Regeneron Pharmaceuticals, Inc.', '12/15/2019');
insert into ProductoNoPerecedor (idProducto, nombreProducto, precio, marca, fechaCaducidad) values ('7670', 'Oxtail - Cut', '$224.13', 'Alliance Resource Partners, L.P.', '12/20/2019');
insert into ProductoNoPerecedor (idProducto, nombreProducto, precio, marca, fechaCaducidad) values ('6980', 'Beef - Ground Lean Fresh', '$238.14', 'Broadridge Financial Solutions, Inc.', '12/12/2019');
