insert into Proveedor (idProveedor, nombreProveedor) values ('50001', 'Gores Holdings II, Inc.');
insert into Proveedor (idProveedor, nombreProveedor) values ('23302', 'Intrexon Corporation');
insert into Proveedor (idProveedor, nombreProveedor) values ('00827', 'ProShares UltraPro Short QQQ');
insert into Proveedor (idProveedor, nombreProveedor) values ('96155', 'Community Trust Bancorp, Inc.');
insert into Proveedor (idProveedor, nombreProveedor) values ('25748', 'Glatfelter');
insert into Proveedor (idProveedor, nombreProveedor) values ('63101', 'State Street Corporation');
insert into Proveedor (idProveedor, nombreProveedor) values ('67726', 'Ligand Pharmaceuticals Incorporated');
insert into Proveedor (idProveedor, nombreProveedor) values ('70731', 'NACCO Industries, Inc.');
insert into Proveedor (idProveedor, nombreProveedor) values ('00461', 'AptarGroup, Inc.');
insert into Proveedor (idProveedor, nombreProveedor) values ('00184', 'NETGEAR, Inc.');
insert into Proveedor (idProveedor, nombreProveedor) values ('05498', 'SecureWorks Corp.');
insert into Proveedor (idProveedor, nombreProveedor) values ('28854', 'EP Energy Corporation');
insert into Proveedor (idProveedor, nombreProveedor) values ('90471', 'GasLog LP.');
insert into Proveedor (idProveedor, nombreProveedor) values ('54985', 'j2 Global, Inc.');
insert into Proveedor (idProveedor, nombreProveedor) values ('90190', 'Safe Bulkers, Inc');
insert into Proveedor (idProveedor, nombreProveedor) values ('70342', 'John Hancock Financial Opportunities Fund');
insert into Proveedor (idProveedor, nombreProveedor) values ('21193', 'Hunter Maritime Acquisition Corp.');
insert into Proveedor (idProveedor, nombreProveedor) values ('74389', 'YPF Sociedad Anonima');
insert into Proveedor (idProveedor, nombreProveedor) values ('14288', 'The RMR Group Inc.');
insert into Proveedor (idProveedor, nombreProveedor) values ('30113', 'Rocky Brands, Inc.');
insert into Proveedor (idProveedor, nombreProveedor) values ('88083', 'Ply Gem Holdings, Inc.');
insert into Proveedor (idProveedor, nombreProveedor) values ('23946', 'Assurant, Inc.');
insert into Proveedor (idProveedor, nombreProveedor) values ('62266', 'Eaton Vance Corporation');
insert into Proveedor (idProveedor, nombreProveedor) values ('37771', 'WEX Inc.');
insert into Proveedor (idProveedor, nombreProveedor) values ('13518', 'Penumbra, Inc.');
insert into Proveedor (idProveedor, nombreProveedor) values ('92176', 'PowerShares DWA Tactical Multi-Asset Income Portfolio');
insert into Proveedor (idProveedor, nombreProveedor) values ('26521', 'American Assets Trust, Inc.');
insert into Proveedor (idProveedor, nombreProveedor) values ('31675', 'Stewart Information Services Corporation');
insert into Proveedor (idProveedor, nombreProveedor) values ('78569', 'Comp En De Mn Cemig ADS');
insert into Proveedor (idProveedor, nombreProveedor) values ('92395', 'Acco Brands Corporation');
insert into Proveedor (idProveedor, nombreProveedor) values ('20086', 'CNO Financial Group, Inc.');
insert into Proveedor (idProveedor, nombreProveedor) values ('77362', 'Retail Properties of America, Inc.');
insert into Proveedor (idProveedor, nombreProveedor) values ('13186', 'TravelCenters of America LLC');
insert into Proveedor (idProveedor, nombreProveedor) values ('44774', 'EnLink Midstream, LLC');
insert into Proveedor (idProveedor, nombreProveedor) values ('17633', 'Tekla Healthcare Investors');
insert into Proveedor (idProveedor, nombreProveedor) values ('78474', 'STRATS Trust');
insert into Proveedor (idProveedor, nombreProveedor) values ('85482', 'Northeast Bancorp');
insert into Proveedor (idProveedor, nombreProveedor) values ('11177', 'PRGX Global, Inc.');
insert into Proveedor (idProveedor, nombreProveedor) values ('69695', 'Adaptimmune Therapeutics plc');
insert into Proveedor (idProveedor, nombreProveedor) values ('72934', 'Selective Insurance Group, Inc.');
insert into Proveedor (idProveedor, nombreProveedor) values ('10543', 'ADMA Biologics Inc');
insert into Proveedor (idProveedor, nombreProveedor) values ('95503', 'Drive Shack Inc.');
insert into Proveedor (idProveedor, nombreProveedor) values ('02973', 'Monmouth Real Estate Investment Corporation');
insert into Proveedor (idProveedor, nombreProveedor) values ('35243', 'AmTrust Financial Services, Inc.');
insert into Proveedor (idProveedor, nombreProveedor) values ('41368', 'RAIT Financial Trust');
insert into Proveedor (idProveedor, nombreProveedor) values ('10256', 'Carnival Corporation');
insert into Proveedor (idProveedor, nombreProveedor) values ('98292', 'Western Alliance Bancorporation');
insert into Proveedor (idProveedor, nombreProveedor) values ('47196', 'First Trust BICK Index Fund');
insert into Proveedor (idProveedor, nombreProveedor) values ('55761', 'KemPharm, Inc.');
insert into Proveedor (idProveedor, nombreProveedor) values ('96678', 'Capitol Acquisition Corp. III');
