use Taqueria;
insert into Sucursal (idSucursal, estado, calle, avenida, numExt, CPS) values (1, 'District of Columbia', 'Crest Line', 'Little Fleur', '2389', '20508');
insert into Sucursal (idSucursal, estado, calle, avenida, numExt, CPS) values (2, 'Georgia', 'Sommers', 'Beilfuss', '411', '30316');
insert into Sucursal (idSucursal, estado, calle, avenida, numExt, CPS) values (3, 'Washington', 'Nova', 'Toban', '682', '98185');
insert into Sucursal (idSucursal, estado, calle, avenida, numExt, CPS) values (4, 'Alabama', 'Meadow Ridge', 'Namekagon', '8915', '36628');
insert into Sucursal (idSucursal, estado, calle, avenida, numExt, CPS) values (5, 'District of Columbia', 'Raven', '2nd', '0515', '20530');
insert into Sucursal (idSucursal, estado, calle, avenida, numExt, CPS) values (6, 'Ohio', 'Buell', '7th', '47849', '43635');
insert into Sucursal (idSucursal, estado, calle, avenida, numExt, CPS) values (7, 'Hawaii', 'Upham', 'Maple Wood', '34', '96820');
insert into Sucursal (idSucursal, estado, calle, avenida, numExt, CPS) values (8, 'Louisiana', 'Hauk', 'Fuller', '5053', '70154');
insert into Sucursal (idSucursal, estado, calle, avenida, numExt, CPS) values (9, 'Tennessee', 'Goodland', 'Golf Course', '181', '37931');
insert into Sucursal (idSucursal, estado, calle, avenida, numExt, CPS) values (10, 'California', 'Melvin', 'Meadow Vale', '3', '91841');
insert into Sucursal (idSucursal, estado, calle, avenida, numExt, CPS) values (11, 'Maryland', 'Mitchell', 'Merchant', '6', '21684');
insert into Sucursal (idSucursal, estado, calle, avenida, numExt, CPS) values (12, 'Texas', 'Warrior', 'Esker', '6', '79159');
insert into Sucursal (idSucursal, estado, calle, avenida, numExt, CPS) values (13, 'Texas', 'Caliangt', 'Mcguire', '01378', '79710');
insert into Sucursal (idSucursal, estado, calle, avenida, numExt, CPS) values (14, 'Arkansas', 'Forest Dale', 'Amoth', '5141', '72905');
insert into Sucursal (idSucursal, estado, calle, avenida, numExt, CPS) values (15, 'Nevada', 'Emmet', 'Schmedeman', '88', '89012');
insert into Sucursal (idSucursal, estado, calle, avenida, numExt, CPS) values (16, 'Arkansas', 'Scott', 'Saint Paul', '376', '72199');
insert into Sucursal (idSucursal, estado, calle, avenida, numExt, CPS) values (17, 'Massachusetts', 'Morningstar', 'Jenifer', '5442', '02453');
insert into Sucursal (idSucursal, estado, calle, avenida, numExt, CPS) values (18, 'California', 'Eastwood', 'Iowa', '77', '90055');
insert into Sucursal (idSucursal, estado, calle, avenida, numExt, CPS) values (19, 'North Carolina', 'Kedzie', 'High Crossing', '704', '27409');
insert into Sucursal (idSucursal, estado, calle, avenida, numExt, CPS) values (20, 'Texas', 'Oakridge', 'Twin Pines', '480', '88553');
